### ISSUE TITLE
Deauther not working

### ISSUE THREAD

**Issue by Pranjal-Prabhat** [tesa-klebeband/ESP32-Deauther#1]

**Comment by tesa-klebeband** [comment]
Hello,
Not sure why you deleted your issue description, but from what I can see what there was before you removed it, it seems like the reason code you are trying to use doesn't work. From what I have tested, reason code 6 and 23 are working as expected, but of course some other may also work. Also, you should see the deauth results pretty quickly, in most cases a few seconds after starting the attack. If you have any more questions, feel free to ask.
Have a great day

**Comment by Pranjal-Prabhat** [comment]
> Hello, Not sure why you deleted your issue description, but from what I can see what there was before you removed it, it seems like the reason code you are trying to use doesn't work. From what I have tested, reason code 6 and 23 are working as expected, but of course some other may also work. Also, you should see the deauth results pretty quickly, in most cases a few seconds after starting the attack. If you have any more questions, feel free to ask. Have a great day

It was due the Hotspot was wpa-3 , I had removed the description,  sorry for inconvenience.
Regards Pranjal Prabhat
